# runs a local version of Epilepsy12 for development on port 8000
# syncs changes in local code folder to the E12 container
# migrates the database

version: '3.9'
services:
  web:
    build: .
    command: >
      sh -c "pip install --upgrade pip &&
             pip install -r requirements/development-requirements.txt &&
             python manage.py collectstatic --noinput &&
             ./s/migrate &&
             ./s/seed &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/home/app/webapp
    environment:
      - E12_POSTGRES_DB_NAME=epilepsy12db
      - E12_POSTGRES_DB_HOST=db
      - E12_POSTGRES_DB_PORT=5432
      - E12_POSTGRES_DB_USER=epilepsy12user
      - E12_POSTGRES_DB_PASSWORD=password
      - E12_SECRET_KEY=mysecretkey
      - E12_DEVELOPMENT_MODE=True
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
  db:
    image: postgres:latest
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=epilepsy12user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=epilepsy12db