##########################
########  README  ########
##########################


# DOCKER COMPOSE FILE FOR DEV VPS DEPLOYMENT

# Runs Epilepsy12 for development on port 8000
# Syncs changes in local code folder to the E12 container
# Starts from empty DB, creates and migrates the database
# Seeds the database with cases, and the RCPCH audit team user

# TODO: remove Volume


version: "3.10"

services:

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/data/:/data/
      - ./caddy/config/:/config/
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  # django application
  django:
    build: .
    ports:
      - 8000:8000 # maps external port 80 to internal port 8000
    links:
      - redis
      - postgis
      - celery
    depends_on:
      - postgis
      - redis
    volumes:
      - .:/app/
    environment:
      # these env vars are ONLY for development
      - E12_POSTGRES_DB_USER=epilepsy12user
      - E12_POSTGRES_DB_PASSWORD=password
      - E12_POSTGRES_DB_NAME=epilepsy12db
      - E12_POSTGRES_DB_HOST=postgis
      - E12_POSTGRES_DB_PORT=5432
      - POSTCODES_IO_API_URL=https://api.postcodes.io
      - RCPCH_CENSUS_PLATFORM_URL=https://api.rcpch.ac.uk/deprivation/v1 # live
      - RCPCH_HERMES_SERVER_URL=http://rcpch-hermes.uksouth.azurecontainer.io:8080/v1/snomed
      - NHS_ODS_API_URL=https://api.nhs.uk/service-search?api-version=2
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - envs/dev-vps.env # env file - NOT committed to Git
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            python manage.py seed --mode=cases --cases 200 &&
            python manage.py seed --mode=seed_registrations &&
            python manage.py seed --mode=seed_groups_and_permissions &&
            python manage.py createsuperuser --noinput || true &&
            echo 'DEV SETUP SCRIPT: Development superuser email: e12-dev-user@rcpch.tech' &&
            echo 'DEV SETUP SCRIPT: Development superuser password: pw' &&
            python manage.py runserver 0.0.0.0:8000"

  # postgres with postgis extension
  postgis:
    image: postgis/postgis:15-3.3
    volumes:
      - "auditenginedb:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=epilepsy12user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=epilepsy12db
      - TZ="Europe/London"

  # redis backend for celery
  redis:
    image: redis:alpine
    expose:
      - 6379

  # celery worker
  celery:
    restart: always
    build:
      context: .
    command: celery -A rcpch-audit-engine worker -l info
    volumes:
      - .:/app
    environment:
      - E12_POSTGRES_DB_USER=epilepsy12user
      - E12_POSTGRES_DB_PASSWORD=password
      - E12_POSTGRES_DB_NAME=epilepsy12db
      - E12_POSTGRES_DB_HOST=postgis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgis
      - redis

  # flower UI for celery tasks
  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persistent=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888 # docker will expose this ports
    volumes:
      - flower_data:/data
    # this will let docker know that we have added a custom volume

  # This is for celery scheduled tasks
  celery-beat:
    build: .
    command: celery -A rcpch-audit-engine beat -l info
    volumes:
      - .:/app
    depends_on:
      - postgis
      - redis

# data volumes
volumes:
  auditenginedb:
  flower_data:

