# runs a local version of Epilepsy12 for development on port 8000
# syncs changes in local code folder to the E12 container
# migrates the database

version: '3.9'

services:
  
  # web container - runs the django app
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/home/app/webapp
    environment:
      # these env vars are ONLY for development
      - E12_POSTGRES_DB_USER=epilepsy12user
      - E12_POSTGRES_DB_PASSWORD=password
      - E12_POSTGRES_DB_NAME=epilepsy12db
      - E12_POSTGRES_DB_HOST=db
      - E12_POSTGRES_DB_PORT=5432
      - E12_SECRET_KEY=mysecretkey
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
      - DJANGO_SUPERUSER_USERNAME=e12-dev-user
      - DJANGO_SUPERUSER_PASSWORD=pw
      - DJANGO_SUPERUSER_FIRST_NAME=dev
      - DJANGO_SUPERUSER_SURNAME=dev
      - DJANGO_SUPERUSER_EMAIL=e12-dev-user@rcpch.tech
      - DJANGO_SUPERUSER_IS_RCPCH_AUDIT_TEAM_MEMBER=True
      - DJANGO_SUPERUSER_ROLE=1
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://localhost,https://0.0.0.0
    command: >
      sh -c "pip install --upgrade pip &&
            pip install -r requirements/development-requirements.txt &&
            python manage.py collectstatic --noinput &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py seed --mode=seed_hospitals &&
            python manage.py seed --mode=seed_semiology_keywords &&
            python manage.py seed --mode=seed_dummy_cases &&
            python manage.py seed --mode=seed_registrations &&
            python manage.py seed --mode=seed_groups_and_permissions &&
            python manage.py createsuperuser --noinput &&
            echo 'DEV SETUP SCRIPT: Development superuser email: e12-dev-user@rcpch.tech' &&
            echo 'DEV SETUP SCRIPT: Development superuser password: pw' &&
            python manage.py runserver 0.0.0.0:8000"
  
  # db container - runs postgres
  db:
    image: postgres:latest
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=epilepsy12user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=epilepsy12db
