# runs a production version of Epilepsy12 in a container on azure on port 8000
# syncs changes in local code folder to the E12 container
# migrates the database

version: "3.10"

services:
  # web container - runs the django app
  web:
    image: e12continerregistry01.azurecr.io/epilepsy12:latest
    container_name: epilepsy12
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    links:
      - redis
      - celery
    depends_on:
      - redis
    volumes:
      - .:/app/
    env_file:
      - .env

    command: >
      sh -c "/opt/venv/bin/python manage.py collectstatic --noinput &&
      /opt/venv/bin/python manage.py migrate &&
      /opt/venv/bin/gunicorn --worker-tmp-dir /dev/shm rcpch-audit-engine.wsgi:application --bind 0.0.0.0:8000"

  # this is the redis backend for celery to run async/caching/cron tasks
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379

  # This is the celery worker
  celery:
    restart: always
    image: e12continerregistry01.azurecr.io/celery:latest
    container_name: celery
    build:
      context: .
    command: /opt/venv/bin/celery -A rcpch-audit-engine worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  # This is for celery cron tasks
  celery-beat:
    image: e12continerregistry01.azurecr.io/celery-beat:latest
    container_name: celery-beat
    build: .
    command: /opt/venv/bin/celery -A rcpch-audit-engine beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
