name: Build and deploy Python app to Azure Web App - epilepsy12

on:
  push:
    branches:
      - '*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Creates fresh git_hash.txt file, adds new current commit hash + branch
      - name: Get Hash and Branch
        id: hash
        run: |
          echo "GIT_BRANCH=$(echo ${GITHUB_REF#refs/heads/}), GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" > git_hash.txt
          cat git_hash.txt
