name: Temp workflow to test Pytest Suite

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v3
      
      - name: List all files
        run: ls -al
      
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install PostGIS dependencies
        run: sudo apt-get install -y binutils libproj-dev gdal-bin libgdal-dev python3-gdal

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      # python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run Pytests
      - name: Pytest Suite
        run: pytest



